// Generated by dts-bundle v0.6.1

declare module 'histria-utils' {
    export { Instance } from 'histria-utils/lib/model/base-object';
    export { ModelManager } from 'histria-utils/lib/factory/model-manager';
    export { Transaction } from 'histria-utils/lib/factory/transaction';
}

declare module 'histria-utils/lib/model/base-object' {
    import { ObservableObject, ObservableArray } from 'histria-utils/lib/model/instance';
    export class Instance implements ObservableObject {
        protected _parent: ObservableObject;
        protected _parentArray: ObservableObject;
        protected _children: any;
        protected _schema: any;
        protected _model: any;
        protected _state: any;
        protected _propertyName: string;
        propertyChanged(propName: string, value: any, oldValue: any, callStackInfo?: any): void;
        stateChanged(propName: string, value: any, oldValue: any, callStackInfo?: any): void;
        protected init(): void;
        protected _setModel(value: any): void;
        modelState(propName: string): any;
        protected getOrSetProperty(propName: string, value?: any): Promise<any>;
        constructor(transaction: any, parent: ObservableObject, parentArray: ObservableArray, propertyName: string, value: any);
        finalize(): void;
    }
}

declare module 'histria-utils/lib/factory/model-manager' {
    export class ModelManager {
        constructor();
        createInstance<T>(classOfInstance: any, transaction: any, value: any): T;
        registerClass(constructor: any, className: string, nameSpace: string): void;
    }
}

declare module 'histria-utils/lib/factory/transaction' {
    export class Transaction {
        constructor();
        create<T>(classOfInstance: any): T;
    }
}

declare module 'histria-utils/lib/model/instance' {
    export interface ObservableObject {
        propertyChanged(propName: string, value: any, oldValue: any, callStackInfo?: any): void;
        stateChanged(stateName: string, value: any, oldValue: any, callStackInfo?: any): void;
        modelState(propName: string): any;
    }
    export interface ObservableArray {
        parent: ObservableObject;
        propertyName: String;
    }
}

