// Generated by dts-bundle v0.6.1

declare module 'histria-utils' {
    export { Instance, InstanceState } from 'histria-utils/lib/model/base-object';
    export { ModelManager } from 'histria-utils/lib/model/model-manager';
    export { Transaction } from 'histria-utils/lib/factory/transaction';
    export { propChanged, init, title, loadRules } from 'histria-utils/lib/model/rules';
    export { State, StringState, IntegerState, EnumState, NumberState, DateState, DateTimeState, RefArrayState, RefObjectState } from 'histria-utils/lib/model/state';
    export { IntegerValue, NumberValue } from 'histria-utils/lib/model/number';
}

declare module 'histria-utils/lib/model/base-object' {
    import { ObservableObject, ObservableArray } from 'histria-utils/lib/model/instance';
    export class InstanceState {
        protected _states: any;
        constructor(parent: ObservableObject, schema: any);
        destroy(): void;
    }
    export class Instance implements ObservableObject {
        protected _parent: ObservableObject;
        protected _parentArray: ObservableObject;
        protected _children: any;
        protected _schema: any;
        protected _model: any;
        protected _states: InstanceState;
        protected _propertyName: string;
        propertyChanged(propName: string, value: any, oldValue: any, callStackInfo?: any): void;
        stateChanged(propName: string, value: any, oldValue: any, callStackInfo?: any): void;
        protected init(): void;
        protected _setModel(value: any): void;
        protected createStates(): void;
        modelState(propName: string): any;
        getOrSetProperty(propName: string, value?: any): Promise<any>;
        constructor(transaction: any, parent: ObservableObject, parentArray: ObservableArray, propertyName: string, value: any);
        dstroy(): void;
        readonly states: InstanceState;
    }
}

declare module 'histria-utils/lib/model/model-manager' {
    export class ModelManager {
        constructor();
        createInstance<T>(classOfInstance: any, transaction: any, value: any): T;
        registerClass(constructor: any, nameSpace: string): void;
        rulesForPropChange(classOfInstance: any, propertyName: string): any[];
        setTitle(classOfInstance: any, method: any, title: string, description?: string): void;
        addRule(classOfInstance: any, ruleType: string, rule: any, ruleParams?: any): void;
    }
}

declare module 'histria-utils/lib/factory/transaction' {
    export class Transaction {
        constructor();
        create<T>(classOfInstance: any): T;
    }
}

declare module 'histria-utils/lib/model/rules' {
    export function title(targetClass: any, title: string, description?: string): (target: any, propertyKey: string, descriptor: PropertyDescriptor) => void;
    export function propChanged(targetClass: any, ...properties: string[]): (target: any, propertyKey: string, descriptor: PropertyDescriptor) => void;
    export function init(targetClass: any): (target: any, propertyKey: string, descriptor: PropertyDescriptor) => void;
    export function loadRules(folder: string): Promise<void>;
}

declare module 'histria-utils/lib/model/state' {
    import { ObservableObject } from 'histria-utils/lib/model/instance';
    export class State {
        protected _parent: ObservableObject;
        protected _propertyName: string;
        protected _stateModel: any;
        protected init(): void;
        constructor(parent: ObservableObject, propertyName: string);
        destroy(): void;
        isDisabled: boolean;
        isHidden: boolean;
        isMandatory: boolean;
        isReadOnly: boolean;
    }
    export class StringState extends State {
    }
    export class NumberState extends State {
        protected init(): void;
        decimals: number;
    }
    export class IntegerState extends State {
    }
    export class DateState extends State {
    }
    export class DateTimeState extends State {
    }
    export class EnumState extends State {
    }
    export class ArrayState extends State {
    }
    export class RefObjectState extends State {
    }
    export class RefArrayState extends State {
    }
}

declare module 'histria-utils/lib/model/number' {
    import { Instance } from 'histria-utils/lib/model/base-object';
    export class BaseNumberValue {
        protected _parent: Instance;
        protected _decimals: number;
        protected _propertyName: string;
        constructor(parent: Instance, propertyName: string);
        protected init(): void;
        destroy(): void;
        value(value?: number): Promise<number>;
        decimals: number;
    }
    export class IntegerValue extends BaseNumberValue {
    }
    export class NumberValue extends BaseNumberValue {
        decimals: number;
    }
}

declare module 'histria-utils/lib/model/instance' {
    export interface ObservableObject {
        propertyChanged(propName: string, value: any, oldValue: any, callStackInfo?: any): void;
        stateChanged(stateName: string, value: any, oldValue: any, callStackInfo?: any): void;
        modelState(propName: string): any;
    }
    export interface ObservableArray {
        parent: ObservableObject;
        propertyName: String;
    }
}

